# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Neuro Database Title by Joyce # feel free to change
description: Created to host neurological health information! # feel free to change
baseurl: /neuro_knowledge_base # the subpath of your site, e.g. /support. # should match name of your github repo
url: https://j0y-ce.github.io # IMPORTANT! change this to whatever the base url of your site is. e.g. your github.io page
permalink: /:categories/:title # don't touch this

content_type: Knowledge Base #Define whether this is a knowledge base, help center, or something else
use_authors: false #Set this to false to disable showing post authors

brand_logo: logo.png  #logo.png . IMPORTANT! put images in the assets folder!
brand_name: NeuroDatabase
header: Brain Imaging Essentials
subheader: An Open-Science Introduction Course to Brain MRI

meta_image: logo.png #odin-meta.png

# Social Links
twitter_username:
facebook_page:
github_username:
email: joyce.li2@mail.mcgill.ca
linkedin_page:
instagram_username:


# Navigation
nav_item_one: White Lab
nav_item_one_link: https://www.lapianalab.com/

nav_item_two: #second external affiliation
nav_item_two_link: #insert link to second external affiliation

nav_item_three: #
nav_item_three_link: #

nav_button: Return to Home
nav_button_link: https://j0y-ce.github.io/neuro_knowledge_base/

# More Help
help_one_title: Collaboration
help_one_content: If you are interested in collaborating with us to use this curriculum at your institution, feel free to reach us through this email!
help_one_button: Email
help_one_link: mailto:joyce.li2@mail.mcgill.ca #"><i class='uil uil-envelope' target="_blank"

help_two_title: Feedback
help_two_content: We love hearing from you! Let us know what your experience was and we can do better
help_two_button: Form
help_two_link: https://forms.office.com/Pages/ResponsePage.aspx?id=cZYxzedSaEqvqfz4-J8J6i673tKSJ-pCgx6_lt_OiNFUMUZZMzI1QUJRQkxCRUFEUzlYMDEwVkpXMC4u

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#


sass:
  sass_dir:          _scss
  style:            :compressed
